# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: greetings.proto

require 'google/protobuf'


descriptor_data = "\n\x0fgreetings.proto\"0\n\x0cHelloRequest\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\"!\n\rHelloResponse\x12\x10\n\x08greeting\x18\x01 \x01(\t23\n\tGreetings\x12&\n\x05Hello\x12\r.HelloRequest\x1a\x0e.HelloResponseb\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

HelloRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("HelloRequest").msgclass
HelloResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("HelloResponse").msgclass
